### ISSUE TITLE
INST ( Institusjonsopphold ) frontend

### ISSUE THREAD

**Issue by mjansrud** [navikt/personopplysninger#171]
- [x] Fjern gruppering av år. Legg inn årstall på hvert enkelt innslag
- [x] Få riktig sortering av innslag. Eldste dato øverst.
- [x] Dropp feltene kategori, registreringstidspunkt og navn
- [x] Skjul teksten "organisasjonsnummer" dersom orgnr ikke finnes på innslaget
- [x] Gjør oppslag på orgnavn basert på perioden (Mulig INST leverer dataen)
- [x] Legg inn kilde

**Comment by Laier68** [comment]
Har påbegynt test fra mitt ståsted i denne saken.
Tar utg.pkt i punktene: 
 1) Fjern gruppering av år. Legg inn årstall på hvert enkelt innslag
 2) Få riktig sortering av innslag. Eldste dato øverst.
 3) Dropp feltene kategori, registreringstidspunkt og navn
 4) Skjul teksten "organisasjonsnummer" dersom orgnr ikke finnes på innslaget
 5) Gjør oppslag på orgnavn basert på perioden (Mulig INST leverer dataen)
 6) Legg inn kilde

Pkt 1) og 3): OK
Pkt 2): Her er skal sortering være nyeste "dato først"mao bare en skrivefeil: OK
Pkt 6) OK 
Pkt 4 og 5): Denne er vanskelig å få testet med de testdataene jeg kan produsere. 

Kan kanskje presiseres hva som faktisk menes med teksten. "Oversikten viser bare registrerte opphold etter 16. september 2020" men det er et spm for fag/prod.eier. 

Inst forhold i Fengsel vises ikke på de testpersonen jeg har generert i Dolly, det er også korrekt ihht spesifikasjonene.

Det gjenstår litt test far mit hold ! oppdaterer fortløpende.
