### ISSUE TITLE
Utskriftstjeneste AA-registeret

### ISSUE THREAD

**Issue by mjansrud** [navikt/personopplysninger#172]
Resterende oppgaver:

- [x] Tekst i footer
- [x] Bytte plass på periode og yrke
- [x] Fikse wrapping av komponenter mellom sider (Komponenter som henger sammen må være på samme side)
- [x] Space mellom fødselsnummer i headeren på PDF-en
- [x] Lage avhukningsbokser for tilleggsvalg
- [x] Teste ny plassering av periode og yrke på oversiktsbildet
- [x] Direkte til utskrift dersom brukeren ikke har tilleggsvalg
- [ ] Få inn orgnr bak orgnavn dersom dataen er tilgjengelig
- [ ] Vise navn i stedet for fødselsnummer for “private arbeidsgivere” (eventuelt kun vis fødselsdato)

**Comment by ojnybo** [comment]
https://stackoverflow.com/c/nav-it/questions/803/807
Kan vi bruke noe herfra?

**Comment by ojnybo** [comment]
Hei. 

Vi har diskutert litt her på Hamar og synes det ser bra ut, men savner en tekst som sier at opplysningene er hentet fra Aa-registeret. Vi synes også vi bør se på muligheter for å begrense antall sider. Vi har følgende forslag:

•	Ikke sideskift mellom timer, permisjoner, utenlandsopphold osv.
•	«Komprimere» opplysningene på side 1
•	«Komprimere» opplysningene i historikk. F.eks. slik:
 
![aa1](https://user-images.githubusercontent.com/47320658/84256874-d0437980-ab14-11ea-8f15-114161e75abb.png)

(Maritime opplysninger bør bare vises dersom arbeidsforholdet er maritimt.)

**Comment by ojnybo** [comment]
[arbeidsforhold utskrift.pdf](https://github.com/navikt/personopplysninger/files/4757813/arbeidsforhold.utskrift.pdf)
Skisse fra Wei

**Comment by chrisarnesen** [comment]
Størrelseforhold mellom viktig info og f.eks paginering på siden (1-5) har fått feil vekting. Relevant info er mye mindre enn hovedinnhold. Man bør se på vektingen her. Font størrelsen som brukes på innholder i tabeller er veldig liten. Kun 9 punkt, dette anbefales ikke på for print. Blir smått :)
11 pkt er anbefalt fra f.eks Blindeforbundet. @ojnybo

**Comment by chrisarnesen** [comment]
Sendt en forespørsel til Wei, om han tar en titt på det @mjansrud 

Noen innspill: Størrelseforhold mellom viktig info og f.eks paginering på siden (1-5) har fått feil vekting.
Relevant info er mye mindre enn hovedinnhold. Man bør se på vektingen her? Font størrelsen som brukes på innholder i tabeller er veldig liten. Kun 9 punkt, dette anbefales ikke på for print. Blir smått :)
11 pkt er anbefalt fra f.eks Blindeforbundet.
Kan man f.eks se på en annen plassering av paginering? Eller er denne infoen veldig viktig? Da ned litt i fontstørrelse på den og tittel, navn og fødsel nummer?
Og øke fontstørrelse på innhold i tabell.

**Comment by mjansrud** [comment]
Utskrift av oversikten over arbeidsforhold:

<img width="531" alt="Skjermbilde 2020-06-15 kl  20 39 03" src="https://user-images.githubusercontent.com/6075402/84759848-8f8da980-afc7-11ea-9c6f-3e5de7b4f470.png">
<img width="553" alt="Skjermbilde 2020-06-16 kl  07 55 49" src="https://user-images.githubusercontent.com/6075402/84759853-91576d00-afc7-11ea-83a8-c85bea422847.png">
[Personopplysning_arbsforhold_nivå1.pdf](https://github.com/navikt/personopplysninger/files/4785821/Personopplysning_arbsforhold_niva1.pdf)
