### ISSUE TITLE
Redesign: Flere opplysninger om deg

### ISSUE THREAD

**Issue by chrisarnesen** [navikt/personopplysninger#186]
Det blir litt mange elementer og blir fort litt uoversiktlig, og det kommer snart 3-4 tjenester til. 

Det er snakk om å flytte det til nivå 2.

**Comment by mjansrud** [comment]
Som nevnt over har det blitt mange elementer under "Flere opplysninger om deg", og planen er å innføre flere. Så kan vi organisere elementene på en annen måte? Ved å innføre en ny side, dropdow, gruppering eller lignende?

![Screenshot 2020-08-05 at 09 03 35](https://user-images.githubusercontent.com/6075402/89382137-91880500-d6fa-11ea-86cf-5d30614da875.png)

**Comment by terjeofnorway** [comment]
Jeg lukker denne oppgaven. Hvis det er aktuelt å gjøre endringer på design og struktur på `personopplysninger`, så blir det en del av en større oppgave foreslår jeg.
