### ISSUE TITLE
Innsyn i MEDL

### ISSUE THREAD

**Issue by ojnybo** [navikt/personopplysninger#191]
Visning av MEDL i personopplysninger

https://app-q2.adeo.no/medl2/swagger-ui.html#/

Formålskode:
N71400 - Nye personvernregler i NAV

**Comment by Laier68** [comment]
Her har jeg påbegynt testing med bruker 10108000398  Aremark Testfamilien
Må etter hvert ha noe flere testbrukere.

**Comment by Laier68** [comment]
Noen sjekkpunkter i test:
1) Hjelpetekster vises.
2) Stikkprøve sjekk av kodeverk "Term" kontra "Tekst" 
![image](https://user-images.githubusercontent.com/60879532/97841367-f77a2d80-1ce5-11eb-8471-a91daed7fded.png)
![image](https://user-images.githubusercontent.com/60879532/97841414-12e53880-1ce6-11eb-8f03-a80a5015e47a.png)
3) Sjekk i Gosys mht til at perioder før 01.01.2015 er filtrert bort. 
Bruker: 06116027036 har flere perioder, før 01.10.2015 ref Gosys, disse vises ikke i PO-MEDL. **OK**

**Comment by Laier68** [comment]
**Observasjoner / feil i test**
Pkt 1) Boks kuttes i underkant (Det er når man peker på spørsmålstegnet.
![image](https://user-images.githubusercontent.com/60879532/97954083-cf043900-1da2-11eb-9fe8-301da54b5316.png)
Pkt 2) Det lå feil versjon av MEDL ute i Q1 31/10. Fikset samme dag (lørdag) av Morten J.   
Pkt 3) Observasjon: Ordlyden er “Kun perioder fra og med 2015 vises.” 
Det er en sannhet med modifikasjoner, da det pt holder at sluttdato er i 2015. 
![image](https://user-images.githubusercontent.com/60879532/97954264-52be2580-1da3-11eb-8d57-7931b1825c89.png)
Pkt 4) Ser at fremtidige perioder vises. .Mulig dette bare er en teknisk konstruksjon i test og ikke vil være realitet i produksjon)  altn at det faktisk skal vises.
![image](https://user-images.githubusercontent.com/60879532/97954366-99ac1b00-1da3-11eb-94b8-64b49ac79249.png)
kt 5) I Gosys ser jeg at perioder som er definert under kategorien "**Under avklaring**" vises. i PO - MEDL.  
Iflg Ole Jonas skal de IKKE det !
![image](https://user-images.githubusercontent.com/60879532/97954436-c7915f80-1da3-11eb-9bd2-6ef315355d07.png)
![image](https://user-images.githubusercontent.com/60879532/97954449-ceb86d80-1da3-11eb-8ec7-fd4bf3930bb5.png)



Deler av testingen dokumenteres i tråden https://nav-it.slack.com/archives/GMNMZ6EDR/p1604298803159800

**Comment by Laier68** [comment]
Det som gjenstår er noen få browser/mobil issues og test av fallback dvs at "Term" benyttes der det ikke finnes "Tekst"
(Mangler en testkanin på det siste )

**Comment by Laier68** [comment]
![Uploading image.png…]()

**Comment by Laier68** [comment]
![image](https://user-images.githubusercontent.com/60879532/99218533-016a5900-27db-11eb-88b1-4f69f1a81f75.png)

**Comment by Laier68** [comment]
Kjører en kjapp stikkprøvebasert sjekk at Term vises korrekt i PO - MEDL
--> Det ser OK ut på en konkret periode (Med MEDLEMSSKAP)
![image](https://user-images.githubusercontent.com/60879532/99393873-488d4280-28de-11eb-9e33-b2d58addbddd.png)

![image](https://user-images.githubusercontent.com/60879532/99394103-a3269e80-28de-11eb-9eb4-0ffa93234f2c.png)

![image](https://user-images.githubusercontent.com/60879532/99394219-d10be300-28de-11eb-8812-04854961392f.png)

![image](https://user-images.githubusercontent.com/60879532/99393953-62c72080-28de-11eb-90cd-8dab671c813f.png)


--> Det ser OK ut på en konkret periode (Uten MEDLEMSSKAP)**
![image](https://user-images.githubusercontent.com/60879532/99394409-1e885000-28df-11eb-8e41-9bb93bd233e7.png)

![image](https://user-images.githubusercontent.com/60879532/99394618-7921ac00-28df-11eb-9aca-dd030b036695.png)

**Comment by Laier68** [comment]
Produksjonssatt 19/11 ca. kl 1035
1) Ikke voldsom mye å verifisere på egen bruker men det som ligger der er korrekt dvs har ingen perioder.
![image](https://user-images.githubusercontent.com/60879532/99651151-87de9f00-2a56-11eb-8660-21b06229db7a.png)
