### ISSUE TITLE
Menypkt "Endre kontonummer/adresse" fra Ditt NAV menyen fungerer ikke fra PO  

### ISSUE THREAD

**Issue by Laier68** [navikt/personopplysninger#195]
En liten bug når man står i PO og trykker på lenken Endre kontonummer/adresse i Ditt NAV menyen.

1) Gå til https://www.nav.no/person/personopplysninger/#adresser
2) Klikk på “Endre kontonummer/adresse” i menyen
3) Resultat: Ingenting skjer og skjermbildet blir grått 
Forventet resultat: Menyen lukkes (og man burde kanskje bli scrollet til riktig posisjon også)

![image](https://user-images.githubusercontent.com/60879532/92566829-1aa3d600-f27d-11ea-9324-6d9571b6f359.png)

**Comment by Laier68** [comment]
Dette er en liten sak men begrenset impact.

**Comment by ojnybo** [comment]
Denne er rettet nå (fra dekoratøren)
