### ISSUE TITLE
Oversett Personopplysninger til engelsk

### ISSUE THREAD

**Issue by mjansrud** [navikt/personopplysninger#198]

**Comment by Laier68** [comment]
Testing pågår
1)  Sjekket stort sett alle tekster inkl. felttekster, feilmeldingstekster fra frontend,, hjelpetekster, lenker. brødsmulestier i 
     Personopplysninger inkl underliggende sider som instopphold, Utlev. av pers.opplysninger, Medl, 
2) Menyene i dekoratøren endrer seg korrekt når man velger engelsk språk i språkvelgeren i PO.
    Valgt språk og meny følger med bruker på de sidene som har engelsk språk eks. Saksoversikt og Kontakt oss.
3) En refresh i PO påvirker ikke valgt språk. 
4) Amplitude (på siden) undersøkelsen vises også på engelsk når engelsk språk er valgt.

**Comment by Laier68** [comment]
Retest av pkt 1) - 6)
1) Usikker på om denne er gjort noe med eller om den faktisk kan gjøres noe med. Ser ingen endring i hvertfall i Q6.
2) 
3)
4) Rettet OK
5) Rettet OK
6) 

7)

**Comment by Laier68** [comment]
Foretatt en kjapp verifikasjon i produksjon, det ser greit ut.

Dog noen vurderinger rundt overgang fra PO engelsk side til en side uten engelsk språkvelger og tilbake igjen.
