### ISSUE TITLE
Endringer i loginservice

### ISSUE THREAD

**Issue by ojnybo** [navikt/personopplysninger#201]
Endring i Loginservice:

**Hva endres?**
Microsoft har besluttet at login.microsoftonline.com for Azure AD B2C slutter å fungere fra og med den 4. desember.
Denne har blitt erstattet av en tilsvarende URL under b2clogin.com
Endringen medfører at URL til discovery/well-known og jwks endepunktene endrer seg i tillegg til issuer i tokenet.

**Hvem treffes?**
Alle som bruker eller validerer tokens (dvs. selvbetjening-idtoken) fra loginservice for borgerrettede apper.

Det vil si, hvis dere har en av følgende URLer noen steder i konfigurasjonen deres:

https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1

**Hva må dere gjøre med appene deres?**
Dere må endre Discovery URL (samt JWKS URL og forventet issuer hvis dere ikke automatisk plukker disse ut fra well known).

For de som benytter token-support skal det holde å endre på propertyen no.nav.security.jwt.issuer.[issuer shortname].discoveryurl
For andre plattformer og rammeverk: sjekk dokumentasjonen

Hvis rammeverket støtter det så kan dere registrere ny issuer på samme endepunkter som dere har eksponert allerede i dag.

**ConfigMap for apper på NAIS**
For å lette arbeidet med å bytte har vi laget et ConfigMap som inneholder gjeldende discovery URL i alle clustrene.

For å få denne inn som en miljøvariabel i poden din må du legge følgende inn i nais.yaml:

...
spec:
  envFrom:
   - configmap: loginservice-idporten

Dette vil tilgjengeliggjøre miljøvariablene:

LOGINSERVICE_IDPORTEN_DISCOVERY_URL
LOGINSERVICE_IDPORTEN_AUDIENCE

Dette er noe dere burde ta i bruk fra og med nå da disse peker på gjeldende verdier.

**Apper utenfor NAIS**
Hvis du ikke er på NAIS så må du manuelt legge inn de nye URLene:

https://navtestb2c.b2clogin.com/navtestb2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1 (dev)
https://navnob2c.b2clogin.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten (prod)

**Jeg vil teste litt på egen hånd**
Hvis du ønsker å tjuvstarte og teste på egen hånd så har vi satt opp loginservice med nye URLer allerede i dag:

https://loginservice-b2clogin-gcp.dev.nav.no (dev-gcp)
https://loginservice-b2clogin-sbs.dev.nav.no (dev-sbs)
https://loginservice-b2clogin.intern.nav.no (prod-gcp)

ConfigMap’et nevnt ovenfor inneholder også miljøvariabelen LOGINSERVICE_IDPORTEN_NEW_DISCOVERY_URL som dere kan bruke i deres egne apper for testingen.

**Når skjer endringene?**
Etter at Loginservice har byttet vil vi oppdatere LOGINSERVICE_IDPORTEN_DISCOVERY_URL i ConfigMap’et nevnt tidligere, og så langt det lar seg gjøre restarte alle applikasjoner som bruker dette.

Om dere opplever feil så bør en restart av applikasjonen deres løse problemet.

Loginservice begynner å utstede tokens med ny URL på følgende datoer:

Dev - Mandag 26. oktober - kl. 09:00
Prod - Mandag 9. november - TBA

Alle har et ansvar for å påse at tjenester de kaller og er avhengige av har oppdaterte URLer. Etter endringen i dev så har vi altså 2 uker til å flushe ut uforutsette problemer før vi endrer i prod.

**Comment by Laier68** [comment]
1) Ved innlogging i tjenesten ser det tilforlatelig ut til å virke OK 
-Ingen feilmeldinger i mot noen tjenester.
![image](https://user-images.githubusercontent.com/60879532/97774124-b3582300-1b55-11eb-8a2f-28cfc389529c.png)
MEN ser ut til å få Internal Server Error på alt som er mulig å editere/oppdatere. (Dette er ikke normal oppførsel da har jeg tatt høyde for de "normale" miljøssuene i PO (q1/q2))

![image](https://user-images.githubusercontent.com/60879532/97774275-8e17e480-1b56-11eb-9d44-688eef60f231.png)

**Comment by Laier68** [comment]
Denne ligger i produksjon allerede så det skal sånn sett være greit.
Input fra Morten J. 
alle har fått en veiledning på å bruke noen miljøvariabler som nais-teamet har satt opp for å få riktige verdier for loginservice
så nå skal alle våre apper bruke de miljøvariablene
så er det bare et tidspspørsmål før de endrer verdiene på variablene i prod
men da skal vi automatisk få oppdaterte verdier
