### ISSUE TITLE
Viser utgåtte landkoder - kontonummer

### ISSUE THREAD

**Issue by ojnybo** [navikt/personopplysninger#204]
Dropdown med liste over valg av land ved registrering av utenlandsk kontonummer viser utgåtte landkoder.

https://kodeverk-web.nais.adeo.no/kodeverksoversikt/kodeverk/Landkoder

Må filtreres slik at vi bare viser gyldige landkoder

**Comment by Laier68** [comment]
Vises litt av hvert av "utgåtte land" mm.

Eks:
![Uploading image.png…]()
![Uploading image.png…]()
