### ISSUE TITLE
Benytt parameter for påkrevd innloggingsnivå fra dekoratøren for login / stepup

### ISSUE THREAD

**Issue by mjansrud** [navikt/personopplysninger#211]

**Comment by Laier68** [comment]
Denne saken og sak https://github.com/navikt/nav-dekoratoren/issues/628 testes samtidig. (2 sider av samme sak)

Hva er testet:

1) Går direkte mot url https://www-q1.nav.no/person/personopplysninger/
--> Velger ruting til VER1 dvs mot innlogging ID-Porten
--> Får da opp KUN opsjon for nivå 4 innlogging, det er korrekt. 
![image](https://user-images.githubusercontent.com/60879532/99870201-87b6de80-2bd1-11eb-8689-bbc6f6870eec.png)

--> Logger inn på Persopplysninger OK (sjekket noen undersider også)
---> Alt oppleves OK (sn4, dittnav meny osv)

2) Foretar innlogging mot fks Ditt NAV med nivå 3
-->Går deretter mot Personopplysninger
--> Velger ruting til VER1 dvs mot innlogging ID-Porten
--> Får da opsjon for stepup i ID-Porten 
![image](https://user-images.githubusercontent.com/60879532/99870125-cd26dc00-2bd0-11eb-9c86-66f0aaf2d7b9.png)
--> Foretar stepup og innlogging med nivå 4 og logges inn OK (m/ n4)
![image](https://user-images.githubusercontent.com/60879532/99870161-39094480-2bd1-11eb-9927-2892687c3324.png)
---> Alt oppleves OK (sn4, dittnav meny osv)

**Oppsummering:**
Det jeg kan si er at alt oppleves riktig og som før, det er jo bra og riktig.  Sånn sett all good !

MEN at det har fungerer som før gjør jo at jeg ikke kan være 100% sikker på hva som skyldes "gml oppsett" og hva som tilskrives parametersettingen.  

Det er ikke testet hvordan dette påvirker en nivå 3 tjeneste, skal det da settes parameter også? eller er dette bare settes for nivå 4 tjenester?

**Comment by Laier68** [comment]
Verifisert OK etter prod.setting

1) Logget inn på fks ditt nav med nivå 3 bruker -> Går mot PO url -> step up til nivå 4-> innlogget PO nivå 4. (Rett nivå fanges opp i endepkt Auth og i ditt nav menyen) OK
2) Gått direkte mot PO ->Innlogging viser kun nivå 4 alternativ-> Logger inn PO. OK
3) Logget inn på fks ditt nav med nivå 4 bruker -> Går mot PO url -> Rett inn på PO nivå 4. OK                                                 4) Logget inn direkte på utbet.oversikt nivå 3 (kun openam token) -> Går direkte mot PO url -> får opp stepup bildet (gjorde ikke test) -> Logger inn med nivå 4 --> Alt OK innlogget PO nivå 4.
