### ISSUE TITLE
Kontonummer - bugs og forbedringer

### ISSUE THREAD

**Issue by ojnybo** [navikt/personopplysninger#214]
Hei! 
Referat fra møte 02.12.20

Takk for møtet i dag, her kommer som avtalt en liten oppsummering. Det er bare å kommentere dersom noe er glemt. 
Infotekster (nav.no)
•	Legge til placeholder, dvs. visning av hvordan IBAN skrives (grå tekst) i tekstinput-feltet. Se på forbedring med eksempel i infoboks for IBAN. Øverste avsnitt i infoboks kunne kanskje vært løftet ut til blå åpen infoboks?
•	Se også på mulighet for et eksempel i infoboks for BIC/SWIFT. 
•	Lenke fra engelsk versjon i blå infoboks fungerte ikke i Q1.
 
Bankens navn og adresse (nav.no og Endre person)
•	Feltene bør settes som obligatoriske både på nav.no og i PDLs "Endre person"-tjeneste dersom BIC/SWIFT ikke er oppgitt.
•	Forslag: vise banknavn- og bankadressefeltene kun når "har ikke BIC/SWIFT" er huket av. 

Valideringstekst bankkode (nav.no)
•	Feil valideringstekst på bankkode for USA, mangler info om land/tall.
Validering av SWIFT (Endre person)
•	Teknisk validering (sendt av Geir): pattern ‘[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}’ for type ‘BICIdentifier’.
•	Se på om dette er validert likt i Endre person.
Validering på tegn i bankens navn og adresse (nav.no og PDL)
•	Enkelte tegn støttes ikke av TPS som f.eks. anførselstegn i bankens navn. Det er litt usikkert på hvordan dette ser ut for bruker som legger det inn på nav.no. Når vi testet i Q1 fikk vi "internal server error". Feilmeldingen fra TPS er "Oppdateringen kunne ikke gjennomføres. Det er et tegn som ikke støttes av systemet." Tekst som ikke godtas er eksempelvis: „Swedbank”, AB". 
•	Her ser vi i PDL/MFN i første omgang på hvordan dette bør valideres hos oss, og kommer med en tilbakemelding.

**Comment by theasteen** [comment]
Er denne gjort @mjansrud ? Finnes det en tidsfrist @ojnybo ?

**Comment by ojnybo** [comment]
Valideringsregler i Person-Mottak (back-end)

**NORSK KONTONUMMER**

Bankkontonummer:

- Påkrevd

- Må være 11 tegn

- Kun siffer

- Må tilfredsstille modulo 11

- Kan ikke være identisk med ident-nummeret

**UTENLANDSK KONTONUMMER**

Bankkontonummer / IBAN:

- Påkrevd

- Maks lengde: 36 tegn (tjenestekontrakten forsikrer dette)

- Kun alfanumeriske tegn

- Kan ikke være identisk med ident-nummeret

Valuta:

- Påkrevd

- Må være en valuta fra valuta-kodeverket

SWIFT/BIC:

- Skal bestå av enten 8 eller 11 tegn

- Kun alfanumeriske tegn

- RegEx (fra Geir Ådnanes):

o Første 6 tegn må være latinske bokstaver (A-Z)

o 7. tegn må være enten en latinsk bokstav eller et tall mellom 2 og 9.

o 8. tegn må være enten en latinsk bokstav mellom A-N og P-Z eller et siffer.

o Hvis SWIFT-koden er lengre enn åtte tegn, skal den få ytterligere tre tegn. 9.-11.tegn skal være alfanumeriske.

o Eks. på godkjente SWIFT-koder: AIOBGT2P, BMETUPQ467S

o Eks. på ikke godkjente SWIFT-koder: IYGHBW1V, FRGTVCMO

Bankkode:

- Maks lengde: 36 tegn

- Skråstrek (/) som første tegn er valgfritt, men får ikke være eneste tegn i koden

- Kun alfanumeriske tegn. Minst ett tegn

- Spesialregler gjelder når bestemte landkoder har blitt valgt (liste fra Geir Ådnanes). Obs! Felles for spesialreglene:

o Én skråstrek som første tegn er valgfritt

o Deretter kan man oppgi latinske bokstaver (valgfritt), fordi ofte vil saksbehandlere ønske å oppgi «/FW», «CC» o.l.

o Siste del av bankkoden må tilfredsstille sifferkravene hvis valgt landkode matcher med en landkode i listen. Er for eksempel landkode «USA» valgt, tillates bankkode-input som /FW123456789, men ikke //123456789, /FW7W123456789, 1234567898, 1234, 123456789ABC

o Spesialreglene:

§ USA – 9 siffer

§ Canada – 9 siffer

§ Australia – 6 siffer

§ Sør-Afrika – 6 siffer

§ New Zealand – 6 siffer

SWIFT eller bankkode:

- Enten SWIFT eller bankkode må fylles ut

Bankens navn:

- Valgfritt hvis SWIFT-kode benyttes

- Påkrevd hvis bankkode benyttes og SWIFT-feltet er tomt

- Maks lengde: 35 tegn

- Kan ikke inneholde «ukjent», «ikke kjent», «vet ikke», «uoppgitt», «n.n.», «nomen nescio»

- Kan ikke bestå av kun whitespace, spesialtegn og/eller sifre

- Kan ikke ha 1+ sammenhengende whitespace’er.

- Aksepterer kun

o latinske bokstaver

o norske bokstaver

o spesialbokstaver (f.eks. ıłŁŊŋŦŧƁɓƊɗƓɠƘƙƤƥƬƭÞþßԈБ) *

o bokstaver med diakritiske tegn**

o siffer

o spesialtegn - . , ‘ / &

o whitespace

Bankens adresse, første linje:

- Valgfritt hvis SWIFT-kode benyttes

- Påkrevd hvis bankkode benyttes og SWIFT-feltet er tomt

- Påkrevd hvis adresselinje 2 er utfylt. «Gap» mellom adresselinjer aksepteres ikke

- Maks lengde: 34 tegn

- Kan ikke inneholde «ukjent», «ikke kjent», «vet ikke», «uoppgitt», «n.n.», «nomen nescio»

- Kan ikke bestå av kun whitespace, spesialtegn og/eller sifre

- Kan ikke ha 1+ sammenhengende whitespace’er.

- Aksepterer kun

o latinske bokstaver

o norske bokstaver

o spesialbokstaver (f.eks. ıłŁŊŋŦŧƁɓƊɗƓɠƘƙƤƥƬƭÞþßԈБ) *

o bokstaver med diakritiske tegn**

o siffer

o spesialtegn - . , : ‘ / & #

o whitespace

Bankens adresse: andre og tredje linje:

- Valgfrie

- Adresselinje 2 er påkrevd hvis adresselinje 3 er utfylt

- Maks lengde per linje: 34 tegn

- Kan ikke inneholde «ukjent», «ikke kjent», «vet ikke», «uoppgitt», «n.n.», «nomen nescio»

- Kan ikke bestå av kun whitespace og spesialtegn

- Aksepterer kun

o latinske bokstaver

o norske bokstaver

o spesialbokstaver*

o bokstaver med diakritiske tegn**

o siffer

o spesialtegn - . , : ‘ / & #

o whitespace

Landkode:

- Påkrevd

* const SPECIAL_LETTERS = 'ıłŁŊŋŦŧƁɓƊɗƓɠƘƙƤƥƬƭÞþßԈБ\\u0189\\u0256\\u00D0\\u00F0\\u00F0\\u0111\\u01E4\\u01E5\\u0187\\u0188\\u01B3\\u01B4'

** Før string’en valideres, normaliserer vi den. Det innebærer at vi først bruker String.prototype.normalize()-metoden på string’en. Det utfører en kanonisk dekomponering (se: NFD) av bokstaver med spesialtegn som vil resultere i flere kodepunkter. F.eks. dekomponering av bokstaven Ç (\u00C7) vil resultere i kodepunktene \u0043 (C) og \u0327 (diakritisk tegn). Deretter strippes kodepunkter for diakritiske tegn (\u0300-\u035f) vekk. Man sitter da igjen med kun "base"-versjonen av bokstaven. F.eks. i string’en: \u0043\u0327 vil \u0327 bli gjenkjent som et diakritisk tegn og dermed strippes vekk. OBS! String’ene blir ikke endret i front-end, men sendt som de er hvis de passerer valideringen. Translittereringen overlates heller til Person-TPS-applikasjonen i PDL nest-sist i verdikjeden.

**Comment by Laier68** [comment]
Tester på denne saken basert på kommentaren fra OJ om valideringsregler. Legger ved eget testdokument.
