### ISSUE TITLE
Kontonummer: Kreve IBAN fra europeiske banker

### ISSUE THREAD

**Issue by ojnybo** [navikt/personopplysninger#241]
Økonomi opplever at mange glemmer å fylle ut landkode foran IBAN-nummeret, og det fører til en del manuelt arbeid. En løsning er å kreve IBAN for europeiske land, da burde vi ta unna de store mengdene.

**Comment by Laier68** [comment]
Testdokumentasjon
**Case A): Valgt europeisk land**
1) Sjekket oppdatert tekst i tooltips 
2) Sjekket oppdatert feilmeldinger (frontend)  
![image](https://user-images.githubusercontent.com/60879532/115238964-8d800400-a11e-11eb-82ae-741b8cb89425.png)
3) Korrekt IBAN kontonr
![image](https://user-images.githubusercontent.com/60879532/115246232-fcad2680-a125-11eb-97e7-0aed06e69462.png)
4) Ikke korrekt IBAN konto nr
![image](https://user-images.githubusercontent.com/60879532/115246409-28c8a780-a126-11eb-9a6a-a5cf01b7454d.png)

**Case B): Ikke europeisk land** 
1) Sjekket at feilmeldinger er uendret (frontend) 
![image](https://user-images.githubusercontent.com/60879532/115244985-c4591880-a124-11eb-902b-70656481672c.png)
2) Sjekket validering er uendret 
![image](https://user-images.githubusercontent.com/60879532/115247700-4d714f00-a127-11eb-87ca-c3ade3471f50.png)

**Comment by Laier68** [comment]
Vi kjører dialogen rundt test av saken i 
https://nav-it.slack.com/archives/C01URBQ5CV9/p1618840968001100

**Comment by Laier68** [comment]
Verifisert OK i produksjon.
