### ISSUE TITLE
Loginservice feiler pga manglende whitelisting av redirect url'er

### ISSUE THREAD

**Issue by anders-nom** [navikt/personopplysninger#253]
Paths som er tiltenkt lenker fra andre tjenester ligger ikke i listene til loginservice (https://github.com/navikt/loginservice/tree/master/src/main/resources).

Eksempel:
`https://www.nav.no/person/personopplysninger/nb/endre-opplysninger/sendt-fra/minprofil/https%3A%2F%2Fwww.nav.no%2Fpselv%2Ftransaksjon%2Fminprofil.jsf%3Fexecution%3De2s1%26from%3Dpo`

Siste segment i disse url'ene er en encodet "return url" som peker tilbake til tjenesten bruker ble sendt fra. Å whiteliste alle varianter her er problematisk, ettersom vi ikke har kontroll på return url'en som andre tjenester setter.

**Comment by Laier68** [comment]
Saken ble testet 3/5
- Foretok innlogging m nivå 3
- Gikk mot Din profil url
- Rutet til Innlogging nivå 4 
- Logget inn ok på tjenesten
Må være test god nok!

**Comment by Laier68** [comment]
Prod.satt 4/5 
Verifisert OK i produksjon.
