### ISSUE TITLE
Midlertidig adresse: Fjerne mulighet for å legge inn ny  midlertidig adresse og erstatte det med lenke til Skatteetaten

### ISSUE THREAD

**Issue by ojnybo** [navikt/personopplysninger#278]
MFN/Team Persondata skal gjøre en del endringer på adresseområdet, i henhold til NAVs Adressepolicy. 

Det er ønskelig at flest mulig av våre brukere oppdaterer sine adresser i Folkeregisteret (Freg). Det har skjedd mye forbedringer hos Skatteetaten, og det har blitt enklere å oppdatere flere adressetyper direkte i Freg, enn det som var mulig tidligere. 

I NAVs selvbetjeningsløsning er det i dag mulig å registrere en kontaktadresse som kan være gyldig i opptil ett år. Kontaktadresse (også kalt postadresse) finnes også i Freg. Når en adresse kun blir registrert i NAV, så vil ingen andre norske etater få tilgang til den. Tidligere ble disse adressene sendt til Freg og registrert der, men det har jurister i Skatteetaten stoppet. Adresser i Freg må komme direkte fra brukeren selv, og ikke via NAV. 

Alle som kan logge seg inn i NAVs selvbetjeningsløsning, kan også logge seg inn hos Skatteetaten. Vi ønsker derfor å fjerne muligheten for å opprette nye kontaktadresser i NAVs selvbetjening, og heller legge inn lenke til Skatteetaten, og informasjon om at NAV bruker adresser som er registrert i Freg, og at man kan registrere andre adressetyper enn bostedsadresse der, inkludert både norske og utenlandske kontaktadresser. Vi ønsker at selvbetjeningsløsningen fortsatt viser hvilke adresser som er registrert i Freg, slik at brukeren enkelt kan se om det er behov for oppdatering i Freg. Det er ingen begrensninger for hvor ofte man kan endre sin kontaktadresse i Freg. Det skal fortsatt være mulig å opphøre en midlertidig adresse.

**Comment by HanneFSivle** [comment]
Informasjon som erstatter registrering av midlertidig adresse:

NAV bruker adresser som er registrert i Folkeregisteret. I Folkeregisteret kan man i tillegg til bostedsadresse, registrere oppholdsadresse og postadresse. 
https://www.skatteetaten.no/person/folkeregister/flytte/endre-postadresse/

**Comment by ojnybo** [comment]
Oppdatert tekst: 
Dersom bruker ikke har en midlertidig adresse registrert:

```
**Midlertidig adresse**
Du har ikke registrert en midlertidig adresse. Hvis du ønsker å få post fra NAV til en midlertidig adresse, kan du registrere oppholdsadresse i Folkeregisteret.
NAV henter adressen din fra Folkeregisteret. Her kan du registrere en midlertidig adresse, (oppholdsadresse), i tillegg til bostedsadresse og postadresse.
```

Lenke:
`Endre adresse i Folkeregisteret`
https://www.skatteetaten.no/person/folkeregister/flytte/endre-postadresse/ 

Når bruker har registrert en midlertidig adresse og kilden er PDL: 

`> Frem til og med<dato> får du post fra NAV til din midlertidige adresse. Du kan slette adressen når som helst.`

Endre-knappen fjernes, bruker skal ha mulighet til å sende inn opphør

Når bruker har registrert en midlertidig adresse og kilden er Freg:

Slette eller endre adresse i Folkeregisteret
https://www.skatteetaten.no/person/folkeregister/flytte/endre-postadresse/
