### ISSUE TITLE
faktisk landkode registreres manuelt på en person i PSAK. Det må avklares hvorfor vi har den koden, hvorfor den kan overstyre landkode fra bostedsadresse og om dette hindrer automatisering.

### ISSUE THREAD

**Issue by PetterLowzow** [navikt/personopplysninger#283]
Jeg har pratet med @kim Næss om faktiskBostedsland. Feltet blir vedlikeholdt når det kommer adresse- og flytte-hendelser fra PDL. Han skal følge opp om det kommer hendelser når "EndrePerson" legger adresse-endringer inn i PDL.

**Comment by PetterLowzow** [comment]
![FaktiskBostedsland brukt 165 gaanger](https://user-images.githubusercontent.com/45782763/135966664-79ae29a8-e0bd-447e-aac5-dae1752c31d5.png)
![Bruk av faktiskBostedsland](https://user-images.githubusercontent.com/45782763/135966667-f639cac8-156b-4d4f-8956-21c20f975b2e.png)

**Comment by PetterLowzow** [comment]
faktiskBostedsland brukes 165 steder.

**Comment by terjeofnorway** [comment]
Ser ut til at denne ble flyttet til et annet prosjekt som nå er lukket, mens selve issuen ble liggende på repoet for `personopplysninger`. Jeg lukker denne issuen nå, så må det heller åpnes en ny på riktig repo.
