### ISSUE TITLE
Personopplysninger: Din profil fra Din pensjon/Uføretrygd gir låsning i skjembildet når man trykker slett

### ISSUE THREAD

**Issue by Laier68** [navikt/personopplysninger#291]
**Personopplysninger: Din profil fra Din pensjon/Uføretrygd gir låsning i skjembildet ved forsøk på slett av tlf.nr** 

- Man får en form for låsning av skjermbildet man får heller ikke foretatt slettingen.  
- Tror dette er en bug som er uavhengig av plattform, skjer i laptop fra chrome, edge og fra mobil iphone safari.
- Øvrig funksjonalitet ser ut til å fungere OK så lenge man ikke forsøker å slette tlf nr initialt.

![image](https://user-images.githubusercontent.com/60879532/143993076-ac54f04b-4c78-46ab-82f9-866356a5b3c0.png)

**Comment by ojnybo** [comment]
Steg 1: Gå til https://www.nav.no/pselv/transaksjon/minprofil.jsf
Steg 2: Trykk "Endre i personopplysninger"

**Comment by terjeofnorway** [comment]
@Laier68 Jeg har funnet feilen, fikset og greier ikke lenger å gjenskape så det skal fungere i dev nå:
https://www.dev.nav.no/person/personopplysninger/nb/endre-opplysninger/sendt-fra/minprofil/https%3A%2F%2Fwww.nav.no%2Fpselv%2Ftransaksjon%2Fminprofil.jsf

Merk at vi er et par stykker som jobber på Personopplysninger-appen, så dersom det er en stund fra jeg skriver dette til du har tid til å verifisere fiksen, så kan det være at jeg må deploye ut til dev på nytt dersom det fortsatt ikke fungerer hos deg.

**Comment by Laier68** [comment]
Test
-Det som utløste at det låste seg var slett av 1) telefonnr og slett av 2)midlertidig adresse.

 1) Jeg har testet at det ikke lengre skjer noen låsning ved slett av tlf nr.  OK
 men
 2) Jeg får ikke testet slett av midlertidig adresse, her er det et eller annen feil (tipper kanskje dette kanskje skyldes flere kokker, men det burde vel ha fungert uansett hva som ligger ute av annen kode ref sak 157 ? Ole Jonas) 
 Forsøker jeg å legge til Midlertidig adresse får jeg bad request, ser at det på mange testkaniner som har reg. midlertidig adresse så vises det invalide date. 
![image](https://user-images.githubusercontent.com/60879532/144180949-4d6f21f3-5914-40cd-891e-1a3ce0227f08.png)

Konklusjon: Tipper det blir OK i produksjon for både case 1) og 2)
