### ISSUE TITLE
Vurdere nåværende visning av Ditt NAV-kontor

### ISSUE THREAD

**Issue by bjornhun** [navikt/personopplysninger#441]
I de nye kontorsidene blir det gjort en del endringer knyttet til åpningstider. Dette bør matches i visningen av "Ditt NAV-kontor" i personopplysninger.

Det er kanskje litt dumt å duplisere denne informasjonen, så kanskje bør vi heller ha en inngang til kontorsiden her i stedet for å vise åpningstidene begge steder. Eventuelt vurdere å skille ut visningen i en felles pakke som kan bruke begge steder.

**Comment by bdahle** [comment]
Testbruker med mange publikumsmottak https://www.nav.no/kontor/nav-vest-telemark
22872948116

**Comment by bdahle** [comment]
- [ ] Svare i Jira-saken når ute

**Comment by bdahle** [comment]
Avventer [svar fra Norg](https://nav-it.slack.com/archives/C0468P7F405/p1710764508050529). Sliter med merkelig 500-feil på sider med flere publikumsmottak

**Comment by bdahle** [comment]
- [ ] Test Tabs helt isolert på en annen side?

**Comment by bdahle** [comment]
Samtlige PRs og ny pakke:
https://github.com/navikt/personopplysninger/pull/517
https://github.com/navikt/nav-enonicxp-frontend/pull/1700
https://github.com/navikt/personopplysninger-api/pull/271
https://github.com/navikt/nav-office-reception-info
