### ISSUE TITLE
Justeringer i infotekster/alertbokser

### ISSUE THREAD

**Issue by bjornhun** [navikt/personopplysninger#466]
Fra Olav:

- Alertboks nummer to fjernes, Teksten blir en vanlig ledetekst. Ingen grunn til at dette skal være en alertboks.

- Teksten i første alertboks justeres.
Jeg regner med at NAV har en saklig grunn til å be om fødselsnummer. Vi ønsker jo ikke klager der vi ikke kan identifisere avsender, det gir ikke mening. Poenget er at folk ikke skriver sensitive personopplysninger om seg selv eller andre. Sensitive opplysninger er ganske mye, fra politisk oppfatning til helseopplysninger. Derfor kan vi forenkle den første setningen til "Ikke send sensitive personopplysninger om deg selv eller andre." Jeg tror det er tilstrekkelig som tiltak. Når vi lenger ned spør om fødselsnummer, tror jeg ikke folk flest oppfatter det som problematisk å oppgi fødselsnummer til NAV.

**Comment by terjeofnorway** [comment]
@bjornhun Er denne oppgaven ferdig? Ser slik ut, men ville bare dobbelsjekke før vi evt lukker den.
