### ISSUE TITLE
Skjermleser ser ut til å lese opp tabell når utloggingsvarsel vises

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/personopplysninger#483]
Legger saken på personopplysninger-repo fordi feilen ikke trigges i noen andre apper når utloggingsvarselet vises. Usikker på hvor den ligger egentlig.

Rapportert fra Morten i UU-teamet:
_En liten ting som jeg ikke skjønner når jeg tar en kjapp titt i dom. Modalen vises slik (det jeg ikke skjønner er hvor den første linja kommer fra, altså at det er en tabell - og det er ikke en tilsvarende tabell slutt):
tabell med 3 kolonner og 6 rader
Du blir snart logget ut automatisk
Vil du fortsatt være innlogget?
Ja Logg ut_

**Comment by bdahle** [comment]
Ikke klart å gjenskape feilen nå, lukker
